create database UserDB;
use UserDB;

CREATE TABLE UserDB.`users` (
  `userid` int(11) NOT NULL AUTO_INCREMENT,
  `firstname` varchar(45) DEFAULT NULL,
  `lastname` varchar(45) DEFAULT NULL,
  `dob` date DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`userid`)
);
CREATE TABLE UserDB.`PRODUCTOS`(
`ID_FAB` VARCHAR(30) NOT NULL,
`ID_PRODUCTO` VARCHAR(30)NOT NULL,
`DESCRIPCION` VARCHAR(30) NOT NULL,
`PRECIO` DOUBLE(10) NOT NULL,
`EXISTENCIAS` INT(10) NOT NULL,
PRIMARY KEY(`ID_PRODUCTO`,`ID_FAB`)
);

CREATE TABLE UserDB.`OFICINAS`(
`OFICINA` INT(3) NOT NULL,
`CIUDAD` VARCHAR(30) NOT NULL,
`REGION` VARCHAR(30) NOT NULL,
`DIR` INT(3) NOT NULL,
`OBJEETIVO` DOUBLE(10) NOT NULL,
`VENTAS` DOUBLE(10) NOT NULL,
PRIMARY KEY(`OFICINA`)
);

CREATE TABLE UserDB.`REPVENTAS`(
`NUM_EMPL` INT(3) NOT NULL,
`NOMBRE` VARCHAR(30) NOT NULL,
`EDAD` INT(3) NOT NULL,
`OFICINA_REP` INT(3),
`TITULO` VARCHAR(30) NOT NULL,
`CONTRATO` DATE NOT NULL,
`DIRECTOR` INT(3),
`CUOTA` DOUBLE(10) NOT NULL,
`VENTAS` DOUBLE(10) NOT NULL,
PRIMARY KEY(`NUM_EMPL`)
);

CREATE TABLE UserDB.`CLIENTES`(
`NUM_CLIE`  int(4) NOT NULL ,
`EMPRESA` VARCHAR(30) NOT NULL,
`REP_CLIE` INT(3) NOT NULL,
`LIMITE_CREDITO` DOUBLE(10) NOT NULL,
PRIMARY KEY (`NUM_CLIE`),
FOREIGN KEY(`REP_CLIE`) REFERENCES UserDB.`REPVENTAS`(`NUM_EMPL`)
);


CREATE TABLE UserDB.`PEDIDOS`(
`NUM_PEDIDO` INT(10)NOT NULL,
`FECHA_PEDIDO` DATE NOT NULL,
`CLIE` INT(4) NOT NULL,
`REP` INT(3) NOT NULL,
`FAB` VARCHAR(30) NOT NULL,
`PRODUCTO` VARCHAR(30) NOT NULL,
`CANT` INT(3) NOT NULL,
`IMPORTE` DOUBLE(10) NOT NULL,
PRIMARY KEY(`NUM_PEDIDO`),
FOREIGN KEY(`CLIE`) REFERENCES UserDB.`PRODUCTOS`(`NUM_CLIE`),
FOREIGN KEY(`FAB`) REFERENCES UserDB.`PRODUCTOS`(`ID_FAB`), 
FOREIGN KEY(`REP`) REFERENCES UserDB.`REPVENTAS`(`NUM_REP`) 
);

ALTER TABLE OFICINAS FOREIGN KEY(`DIR`) REFERENCES UserDB.`REPVENTAS`(`DIRECTOR`);
ALTER TABLE REPVENTAS FOREIGN KEY(`OFICINA_REP`) REFERENCES UserDB.`OFICINAS`(`OFICINA_REP`);